config/routes.rb
Empty::Application.routes.draw do

	root :to => "home#index"

  match '/Sitemap.xml' => "sitemap#index"
  match '/rss-solutions.xml' => "rss#solutions"
  match '/rss-catalog.xml' => "rss#catalog"
  match '/sitemap.xml' => "sitemap#index"
	match "orders/new" => "orders#create", :via => :post

	match "delivery" => "home#delivery"
	match "guaranty" => "home#guaranty"

	match "email" => "email#index"

	match "orders/contact" => "orders#contact"
	match "orders/success" => "orders#success_order"

	match "orders/new" => "orders#index"

	match "catalog/led_lighting" => "catalog#led_lighting"
	match "catalog/uninterruptible_power" => "catalog#uninterruptible_power"
	match "catalog/invertors" => "catalog#invertors"
	match "catalog/wind-turbins" => "catalog#wind_turbines"
  match "catalog/wind_generator" => "catalog#wind_generator"
	match "catalog/batteries-hzb-6-12v" => "catalog#batteries_hzb_6_12v"
	match "catalog/batteries-hzb-fa-12v" => "catalog#batteries_hzb_fa_12v"
	match "catalog/batteries-hzs-4-6-12v" => "catalog#batteries_hzs_4_6_12v"
	match "catalog/batteries-hzb-2v" => "catalog#batteries_hzb_2v"
	match "catalog/batteries-hzy-6-12v" => "catalog#batteries_hzy_6_12v"
	match "catalog/batteries-hzy-fa-12v" => "catalog#batteries_hzy_fa_12v"
	match "catalog/batteries-hzy-12v" => "catalog#batteries_hzy_12v"
	match "catalog/batteries-traction" => "catalog#batteries_traction"
	match "catalog/self_power_gas" => "catalog#self_power_gas"
	match "catalog/self_power_gasoline" => "catalog#self_power_gasoline"
	match "catalog/solar-panels" => "catalog#solar_panels"
	match "catalog/optico_acust_ke_doa" => "catalog#optico_acust_ke_doa"
  match "catalog/led_lighting_ke_ccd_184" => "catalog#led_lighting_ke_ccd_184"
  match "catalog/led_lighting_ke_ccd_star" => "catalog#led_lighting_ke_ccd_star"
  match "catalog/led_lighting_ke_ccd_tl418_cl1_2400" => "catalog#led_lighting_ke_ccd_tl418_cl1_2400"

	match "catalog/:alias" => "articles#show"

	match "search" => "search#index"
	match "catalog" => "catalog#index"
	match "about" => "articles#show", :alias => "about"
	match "technologies" => "technologies#index"
	match "solutions" => "solutions#index"
	match "company" => "company#index"

	match "solutions/ind-power-give" => "solutions#ind_power_give"
	match "solutions/unint-power-heating" => "solutions#unint_power_heating"
	match "solutions/electrification-country-house" => "solutions#electrification_country_house"
	match "solutions/autonomous-system-stand-sol" => "solutions#autonomous_system_stand_sol"
	match "solutions/uninterrupted-power-supply-stand-sol" => "solutions#uninterrupted_power_supply_stand_sol"
	match "solutions/energy-efficient-lighting-jkh-220v-50hz" => "solutions#energy_efficient_lighting_jkh_220v_50hz"
	match "catalog/(:alias)" => "articles#show"

	match "admin/accounts/add" => "admin/accounts#add"
	match "admin/login" => "admin/accounts#login"

	namespace :admin do
		resources :articles
	end
	match "home" => "home#index"
	match ':value' => "home#index"
 	match "index.php?page=catalog&category=map" => "home#index"
	match ':value(/:value2(/value3))' => "home#index"
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
	def index
		@invertors = 'invertors'
		@self_power_gasoline = 'self_power_gasoline'
		@uninterruptible_power = "uninterruptible_power"
		@wind_generator = "wind_generator"
		@led_lighting = "@led-lighting"
	end

	def led_lighting

	end

	def uninterruptible_power

	end

	def invertors

  end

  def led_lighting_ke_ccd_tl418_cl1_2400

  end

  def led_lighting_ke_ccd_star

  end

  def led_lighting_ke_ccd_184

  end

	def wind_turbines

	end

	def batteries_hzb_6_12v

	end

	def batteries_hzb_fa_12v

	end

	def batteries_hzs_4_6_12v

	end

	def batteries_hzb_2v

	end

	def batteries_hzy_6_12v

	end

	def batteries_hzy_fa_12v

	end

	def batteries_hzy_12v

	end

	def batteries_traction

	end

	def self_power_gas

	end

	def self_power_gasoline

	end

	def solar_panels

	end

	def optico_acust_ke_doa

	end

end

app/views/catalog/batteries_hzb_6_12v.html.erb
<%= content_for :page_name do %>Технология AGM - HZB 6, 12V аккумуляторные батареи<% end %>
<%= content_for :title do %>Аккумуляторные батареи на основе технологии AGM - HZB 6, 12V <% end %>
<%= content_for :keywords do %>аккумуляторы haze, аккумуляторы haze hzb, свинцово-кислотные аккумуляторы, необслуживаемые аккумуляторы, agm hzb 6v, agm hzb 12v, hzb<% end %>
<%= content_for :description do %>Герметичные необслуживаемые аккумуляторы HAZE, относятся к классу стационарных свинцово-кислотных аккумуляторов с системой рекомбинации газов - тип VRLA<% end %>
<% scale = 0.15 %>
<div id="product">
	<div class="product-description">
  		<strong>Стационарные аккумуляторные батареи</strong>
		<br />
  		Срок службы: 12 лет
		<br />
  		Диапазон емкости: 15...230 Ач
		<br />
		<p />
		Необслуживаемые герметизированные <strong>свинцово-кислотные аккумуляторные батареи</strong> <strong>Haze</strong> <strong>HZB</strong>
		изготовлены с высочайшими стандартами качества. Отсутствует необходимость технического обслуживания <strong>аккумуляторных батарей</strong>. Аккумуляторы Haze устойчивы к глубокому разряду в соответствии c DIN 43539 T5
	</div>
	<div class="description-price">
  		*Цены актуальны на 30 июня, их необходимо уточнить по тел. 8 (915) 266-87-30 или воспользоваться <a href="orders/new">формой оформления заявки</a>
	</div>
	<table class="catalog-table" cellspacing="0" cellpadding="0">
		<thead>
		<tr>
			<th rowspan="2">Модель</th>
			<th rowspan="2">Номинальное напряжение, В</th>
			<th rowspan="2">Номинальная емкость, Ач</th>
			<th rowspan="2">Емкость С20 1,75 В/эл 20°С, Ач</th>
			<th rowspan="2">Емкость С10 1,80 В/эл 20°С, Ач</th>
			<th rowspan="2">Ток заряда макс., А</th>
			<th rowspan="2">Мощность, 10 мин., 1,75 В/эл, Вт/эл</th>
			<th colspan="3">Габаритные размеры, мм</th>
			<th rowspan="2">Вес, кг</th>
			<th rowspan="2">Внутреннее сопрот., мОм</th>
			<th rowspan="2">*Цена, руб.</th>
		</tr>
		<tr>
  			<th>Длина</th>
  			<th>Ширина</th>
  			<th>Высота</th>
		</tr>
		</thead>
		<tbody>
			<tr>
				<td><strong>HZB6-110</strong></td>
				<td>6</td>
				<td>110</td>
				<td>109</td>
				<td>94.9</td>
				<td>27</td>
				<td>476</td>
				<td>193</td>
				<td>168</td>
				<td>205</td>
				<td>16.0</td>
				<td>4</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB6-160</strong></td>
				<td>6</td>
				<td>160</td>
				<td>167</td>
				<td>152</td>
				<td>40</td>
				<td>638</td>
				<td>298</td>
				<td>171</td>
				<td>226</td>
				<td>26.0</td>
				<td>2</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB6-200</strong></td>
				<td>6</td>
				<td>200</td>
				<td>193</td>
				<td>172</td>
				<td>50</td>
				<td>661</td>
				<td>318</td>
				<td>170</td>
				<td>225</td>
				<td>31.0</td>
				<td>&lt;2</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB12-15T</strong></td>
				<td>12</td>
				<td>15</td>
				<td>17.6</td>
				<td>15.2</td>
				<td>4</td>
				<td>70.9</td>
				<td>200</td>
				<td>76</td>
				<td>123</td>
				<td>5.14</td>
				<td>18</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB12-18</strong></td>
				<td>12</td>
				<td>18</td>
				<td>17.8</td>
				<td>15.3</td>
				<td>4.5</td>
				<td>72.0</td>
				<td>181</td>
				<td>76</td>
				<td>167</td>
				<td>6.25</td>
				<td>17.1</td>
				<td>1364</td>
			</tr>
			<tr>
				<td><strong>HZB12-26</strong></td>
				<td>12</td>
				<td>26</td>
				<td>26.7</td>
				<td>23.4</td>
				<td>6.5</td>
				<td>120</td>
				<td>166</td>
				<td>176</td>
				<td>126</td>
				<td>9.2</td>
				<td>11</td>
				<td>2373</td>
			</tr>
			<tr>
				<td><strong>HZB12-28</strong></td>
				<td>12</td>
				<td>28</td>
				<td>27.4</td>
				<td>23.4</td>
				<td>7</td>
				<td>116</td>
				<td>166</td>
				<td>125</td>
				<td>175</td>
				<td>9.4</td>
				<td>11</td>
				<td>2357</td>
			</tr>
			<tr>
				<td><strong>HZB12-33</strong></td>
				<td>12</td>
				<td>33</td>
				<td>32.8</td>
				<td>28.3</td>
				<td>8</td>
				<td>148</td>
				<td>195</td>
				<td>130</td>
				<td>160</td>
				<td>10.9</td>
				<td>8.5</td>
				<td>2871</td>
			</tr>
			<tr>
				<td><strong>HZB12-40T</strong></td>
				<td>12</td>
				<td>40</td>
				<td>37.5</td>
				<td>35.3</td>
				<td>10</td>
				<td>177</td>
				<td>194</td>
				<td>250</td>
				<td>93.5</td>
				<td>13.3</td>
				<td>7</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB12-44</strong></td>
				<td>12</td>
				<td>44</td>
				<td>40.6</td>
				<td>35.9</td>
				<td>11</td>
				<td>200</td>
				<td>197</td>
				<td>165</td>
				<td>170</td>
				<td>13.6</td>
				<td>7.5</td>
				<td>3522</td>
			</tr>
			<tr>
				<td><strong>HZB12-55</strong></td>
				<td>12</td>
				<td>55</td>
				<td>53</td>
				<td>45.8</td>
				<td>14</td>
				<td>248</td>
				<td>228</td>
				<td>137</td>
				<td>207</td>
				<td>17.5</td>
				<td>6.5</td>
				<td>4560</td>
			</tr>
			<tr>
				<td><strong>HZB12-70J</strong></td>
				<td>12</td>
				<td>70</td>
				<td>64.8</td>
				<td>56</td>
				<td>18</td>
				<td>294</td>
				<td>350</td>
				<td>167</td>
				<td>179</td>
				<td>22.1</td>
				<td>5</td>
				<td>5507</td>
			</tr>
			<tr>
				<td><strong>HZB12-70</strong></td>
				<td>12</td>
				<td>70</td>
				<td>66.1</td>
				<td>57.2</td>
				<td>18</td>
				<td>300</td>
				<td>259</td>
				<td>168</td>
				<td>208</td>
				<td>21.5</td>
				<td>5</td>
				<td>5635</td>
			</tr>
			<tr>
				<td><strong>HZB12-80</strong></td>
				<td>12</td>
				<td>80</td>
				<td>76.1</td>
				<td>65.9</td>
				<td>20</td>
				<td>318</td>
				<td>259</td>
				<td>168</td>
				<td>208</td>
				<td>23.7</td>
				<td>5</td>
				<td>6331</td>
			</tr>
			<tr>
				<td><strong>HZB12-90</strong></td>
				<td>12</td>
				<td>90</td>
				<td>86.3</td>
				<td>75.7</td>
				<td>22</td>
				<td>372</td>
				<td>305</td>
				<td>168</td>
				<td>208</td>
				<td>29.0</td>
				<td>4</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB12-100</strong></td>
				<td>12</td>
				<td>100</td>
				<td>95.7</td>
				<td>85.1</td>
				<td>25</td>
				<td>426</td>
				<td>305</td>
				<td>168</td>
				<td>208</td>
				<td>30.0</td>
				<td>4</td>
				<td>7176</td>
			</tr>
			<tr>
				<td><strong>HZB12-110</strong></td>
				<td>12</td>
				<td>110</td>
				<td>107</td>
				<td>85.1</td>
				<td>27</td>
				<td>467</td>
				<td>332</td>
				<td>174</td>
				<td>213</td>
				<td>32.2</td>
				<td>4</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB12-120</strong></td>
				<td>12</td>
				<td>120</td>
				<td>116</td>
				<td>104</td>
				<td>30</td>
				<td>498</td>
				<td>408</td>
				<td>176</td>
				<td>227</td>
				<td>35.0</td>
				<td>3</td>
				<td><%= (6305*scale + 6305).round %></td>
			</tr>
			<tr>
				<td><strong>HZB12-135</strong></td>
				<td>12</td>
				<td>135</td>
				<td>128</td>
				<td>115</td>
				<td>35</td>
				<td>553</td>
				<td>340</td>
				<td>173</td>
				<td>280</td>
				<td>39.6</td>
				<td>2.73</td>
				<td>8928</td>
			</tr>
			<tr>
				<td><strong>HZB12-150</strong></td>
				<td>12</td>
				<td>150</td>
				<td>145</td>
				<td>128</td>
				<td>38</td>
				<td>560</td>
				<td>482</td>
				<td>170</td>
				<td>242</td>
				<td>44.2</td>
				<td>2.5</td>
				<td>9201</td>
			</tr>
			<tr>
				<td><strong>HZB12-160</strong></td>
				<td>12</td>
				<td>160</td>
				<td>160</td>
				<td>146</td>
				<td>40</td>
				<td>614</td>
				<td>530</td>
				<td>209</td>
				<td>214</td>
				<td>52.2</td>
				<td>2</td>
				<td>уточнить</td>
			</tr>
			<tr>
				<td><strong>HZB12-200</strong></td>
				<td>12</td>
				<td>200</td>
				<td>193</td>
				<td>172</td>
				<td>50</td>
				<td>661</td>
				<td>520</td>
				<td>240</td>
				<td>220</td>
				<td>66.0</td>
				<td>&lt;2</td>
				<td><%= (10696*scale + 10696).round %></td>
			</tr>
			<tr>
				<td><strong>HZB12-230</strong></td>
				<td>12</td>
				<td>230</td>
				<td>223</td>
				<td>200</td>
				<td> 57</td>
				<td>681</td>
				<td>521</td>
				<td>269</td>
				<td>203</td>
				<td>70.0</td>
				<td>&lt;2</td>
				<td>17385</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/catalog/batteries_traction.html.erb
<%= content_for :page_name do %>Тяговые аккумуляторы<% end %>
<%= content_for :title do %>Технологии GEL - Тяговые аккумуляторы<% end %>
<%= content_for :keywords do %>aккумуляторные батареи, тяговые аккумуляторы, gel<% end %>
<%= content_for :description do %>Тяговые аккумуляторы производятся в соответствии с требованиями Европейских стандартов и применяются для всех видов напольного электротранспорта<% end %>
<div id="product">
	<div class="product-description">
		<strong>Аккумуляторные батареи</strong> серии EV для электромашин
		<br/>
		Срок службы: 12
		<br/>
		Диапазон емкости: 7,5 - 230 Ач
		<br/>
		<p/>
		<strong>Тяговые аккумуляторы</strong> производятся в соответствии с требованиями Европейских стандартов
		и применяются для всех видов напольного электротранспорта.
	</div>
	<div class="description-price">
		Цены необходимо уточнить по телефону по тел. 8 (915) 266-87-30 или воспользоваться <a href="orders/new">формой оформления заявки</a>
	</div>
	<table class="catalog-table">
		<tbody>
		<tr>
			<td colspan="2">Технические характеристики</td>
		</tr>
		<tr>
			<td>Номинальное напряжение</td>
			<td>6, 12</td>
		</tr>
		<tr>
			<td>Срок службы</td>
			<td>12</td>
		</tr>
		<tr>
			<td>Диапазон рабочих температур</td>
			<td>-20 - +50С</td>
		</tr>
		<tr>
			<td>Сплав решетки</td>
			<td>PbCaSn</td>
		</tr>
		<tr>
			<td>Пластины</td>
			<td>Намазные</td>
		</tr>
		<tr>
			<td>Сепаратор</td>
			<td>Стекловолокно</td>
		</tr>
		<tr>
			<td>Активный материал</td>
			<td>свинец</td>
		</tr>
		<tr>
			<td>Материал корпуса</td>
			<td>ABS</td>
		</tr>
		<tr>
			<td>Зарядное напряжение</td>
			<td>(max)2.41 В/эл.</td>
		</tr>
		<tr>
			<td>Электролит</td>
			<td>серная кислота</td>
		</tr>
		<tr>
			<td>Предохранительный клапан</td>
			<td></td>
		</tr>
		<tr>
			<td>Выводы</td>
			<td>Вставка под болт, Авто</td>
		</tr>
		<tr>
			<td>Момент затяжки</td>
			<td></td>
		</tr>
		<tr>
			<td>Соединители</td>
			<td></td>
		</tr>
		<tr>
			<td>Типичная область применения</td>
			<td>Машины на электротяге</td>
		</tr>
		</tbody>
	</table>
</div>

app/views/catalog/index.html.erb
<% content_for :page_name do %>Каталог продукции
<% end %>
<% content_for :keywords do %>инверторы, автономное электрописание, бесперебойное электропитание, ветрогенераторы, МАП Энергия LCD, оптико-акустические датчики, КЭ-ДОА,акустические датчики,
<% end %>
<% content_for :description do %>Каталог продукции. Оптико-акустические датчики движения КЭ-ДОА. Аккумуляторные батареи. Инверторы. Ветрогенераторы. Системы автономного электропитания.
<% end %>
<% content_for :title do %>Каталог продукции - Оптико-акустические датчики движения КЭ-ДОА. Аккумуляторные батареи. Инверторы. Ветрогенераторы. Системы автономного электропитания.
<% end %>
<% invertors_url = url_for :controller => :catalog, :action => :invertors %>
<div class="catalog-items">
  <div>
    <h1>Датчики движения</h1>

    <div class="line">
      <hr>
    </div>
    <div class="clear-both"></div>
    <div class="catalog-item">
      <a href="/catalog/optico_acust_ke_doa" title="Оптико-акустические датчики движения КЭ-ДОА">
        <div class="body">
          <img src="/images/products/optico-acust-ke-doa/small.png" alt="Оптико-акустические датчики движения КЭ-ДОА" title="Оптико-акустические датчики движения КЭ-ДОА"/>

          <h2>Оптико-акустические датчики движения КЭ-ДОА</h2>
        </div>
      </a>
    </div>
    <div class="clear-both"></div>

  </div>
  <div>
    <h1>Аккумуляторные батареи на основе технологии AGM</h1>

    <div class="line">
      <hr>
    </div>
    <div class="clear-both"></div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzb-6-12v" title="HZB 6, 12V Моноблок">
        <div class="body">
          <img src="/images/products/batteries-hzb-6-12v/small.png" alt="HZB 6, 12V Моноблок" title="HZB 6, 12V Моноблок"/>

          <h2>HZB 6, 12V Моноблок</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzb-fa-12v" title="HZB FA 12V Моноблок">
        <div class="body">
          <img src="/images/products/batteries-hzb-fa-12v/small.png" alt="HZB FA 12V Моноблок" title="HZB FA 12V Моноблок"/>

          <h2>HZB FA 12V Моноблок</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzs-4-6-12v" title="HZS 4, 6 & 12V Моноблок">
        <div class="body">
          <img src="/images/products/batteries-hzs-4-6-12v/small.png" alt="HZS 4, 6 & 12V Моноблок" title="HZS 4, 6 & 12V Моноблок"/>

          <h2>HZS 4, 6 & 12V Моноблок</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzb-2v" title="HZB 2V Аккумулятор">
        <div class="body">
          <img src="/images/products/batteries-hzb-2v/small.png" alt="HZB 2V Аккумулятор" title="HZB 2V Аккумулятор"/>

          <h2>HZB 2V Аккумулятор</h2>
        </div>
      </a>
    </div>
  </div>
  <div class="clear-both"></div>
  <div class="catalog-items">
    <h1>Инверторы, Ветрогенераторы</h1>

    <div class="line">
      <hr>
    </div>
    <div class="clear-both"></div>
    <div class="catalog-item">
      <a href="<%= invertors_url %>" title="Инверторы">
        <img src="/images/products/invetors/small.png" alt="Инверторы" title="Инверторы"/>

        <h2>Инверторы</h2>
      </a>
    </div>
    <div class="catalog-item">
      <a href="catalog/self_power_gas" title="Системы автономного электропитания (газ)">
        <div class="body">
          <img src="/images/products/self_power/small_gas.png" alt="Системы автономного электропитания (газ)" title="Системы автономного электропитания (газ)"/>

          <h2>Системы автономного электропитания (газ)</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="catalog/self_power_gasoline" title="Системы автономного электропитания (бензин)">
        <div class="body">
          <img src="/images/products/self_power/small_gasoline.png" alt="Системы автономного электропитания (бензин)" title="Системы автономного электропитания (бензин)"/>

          <h2>Системы автономного электропитания (бензин)</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href=" <%= url_for :controller => :catalog, :action => :uninterruptible_power %>" title="Системы бесперебойного электропитания">
        <div class="body">
          <img src="/images/products/uninterruptible_power/small.png" alt="Системы бесперебойного электропитания" title="Системы бесперебойного электропитания"/>

          <h2>Системы бесперебойного электропитания</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="<%= url_for :controller => :catalog, :action => :wind_turbines %>" title="Ветрогенераторы">
        <div class="body">
          <img src="/images/products/wind_generator/small.png" alt="Ветрогенераторы" title="Ветрогенераторы"/>

          <h2>Ветрогенераторы</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/led_lighting" title="LED светильники">
        <div class="body">
          <img src="/images/products/led_lighting/small.png" alt="LED светильники" title="LED светильники"/>

          <h2>LED светильники</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/solar-panels" title="Солнечные батареи">
        <div class="body">
          <img src="/images/products/solar_panels/small.png" alt="Солнечные батареи" title="Солнечные батареи">

          <h2>Солнечные батареи</h2>
        </div>
      </a>
    </div>
  </div>
  <div class="clear-both"></div>
  <div class="catalog-items">
    <h1>Аккумуляторные батареи на основе технологии GEL</h1>

    <div class="line">
      <hr>
    </div>
    <div class="clear-both"></div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzy-6-12v" title="HZY 6, 12V Моноблок">
        <div class="body">
          <img src="/images/products/batteries_hzy_6_gel/small.png" alt="GEL - HZY 6, 12V Моноблок" title="GEL - HZY 6, 12V Моноблок"/>

          <h2>HZY 6, 12V Моноблок</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzy-fa-12v" title="HZY FA 12V Моноблок">
        <div class="body">
          <img src="/images/products/batteries_hzy_fa_12v/small.png" alt="HZY FA 12V Моноблок" title="HZY FA 12V Моноблок"/>

          <h2>HZY FA 12V Моноблок</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/batteries-hzy-12v" title="HZY 2V Аккумулятор">
        <div class="body">
          <img src="/images/products/batteries_hzy-2v/small.png" alt="HZY 2V Аккумулятор" title="HZY 2V Аккумулятор"/>

          <h2>HZY 2V Аккумулятор</h2>
        </div>
      </a>
    </div>
    <div class="catalog-item">
      <a href="/catalog/batteries-traction" title="Тяговые аккумуляторы">
        <div class="body">
          <img src="/images/products/batteries_traction/small.png" alt="Тяговые аккумуляторы" title="Тяговые аккумуляторы"/>

          <h2>Тяговые аккумуляторы</h2>
        </div>
      </a>
    </div>
  </div>
  <div class="clear-both"></div>
</div>